### ISSUE TITLE
Versioning issues

### ISSUE THREAD

**Issue by fasteasyfree** [vndee/local-rag-example#2]
Would it be possible to produce a requirements.txt (with versions) for pip? I'm attempting to implement, but hitting various obstacles. default `pip install langchain` means it complains about needing to import various libraries from langchain_community.

I've installed the libraries released prior to your 1st Dec commit:

```python
pip install langchain==0.0.343 streamlit==1.28.2 streamlit_chat chromadb==0.4.18 pypdf==3.17.1 fastembed==0.1.0
```
But I'm still getting an error:
```
/home/USERNAME/anaconda3/envs/py310/lib/python3.10/site-packages/langchain_core/vectorstores.py:325: UserWarning: No relevant docs were retrieved using the relevance score threshold 0.5
  warnings.warn(
```

Any assistance would be appreciated! I've tried with both python 3.10 and 3.11 environments, but 3.11 gives the following warning on running app.py: `gio: http://localhost:8501: Operation not supported`

Thanks.

**Comment by fasteasyfree** [comment]
Update: Ok, not sure what I did differently on a new run, but despite the warning running under 3.11 it's launched, handled a document upload and managed to respond to a query.

**Comment by Aks11-11** [comment]
To generate a requirements.txt file with versions for your Python project, you can use pip freeze. This command lists all installed packages and their versions. You can direct the output of pip freeze to a text file, which will serve as your requirements.txt.

Here's how you can do it:

First, activate your virtual environment if you're using one.
Run pip freeze > requirements.txt in your terminal. This command will generate a requirements.txt file containing all installed packages and their versions.
However, if you want to ensure compatibility with the specific versions you mentioned, you can manually create a requirements.txt file with those versions. Here's how your requirements.txt should look based on the versions you provided:

makefile
Copy code
langchain==0.0.343
streamlit==1.28.2
streamlit_chat
chromadb==0.4.18
pypdf==3.17.1
fastembed==0.1.0
Once you have your requirements.txt file, you can install the dependencies with:

bash
Copy code
pip install -r requirements.txt
Regarding the warning you mentioned (Operation not supported), it seems related to gio, which is part of GNOME's GIO library. This warning might be specific to the environment or configuration you're running your application in. If it's not causing any functional issues, you might choose to ignore it. Otherwise, you may need to investigate further to understand why it's being triggered.
